import type { NextPage } from 'next';
import Head from 'next/head';

import Ratio from '../components/Ratio';
import MyStopwatch from '../components/Timer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ratio</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>

      <main className='flex flex-col items-center justify-center h-screen border-2'>
        <Ratio />
      </main>
    </div>
  );
};

export default Home;
